svg-sprite/svg-sprite

- README.md
I ran locally a script based on the source code bellow and so I realized there were some typos.
> typos in script using glob and vinyl

- package.json
The latest `svgo` patch fixes some issues with svg paths optimization. Much needed, otherwise resulting in glitched svg sprites.
> SVGO Version Bump

- lib/svg-sprite/shape.js
Suggestion to fix this issue: https://github.com/jkphl/svg-sprite/issues/109
> Issue https://github.com/jkphl/svg-sprite/issues/109

- README.md
> Mention namespaceClassnames in the readme

- lib/svg-sprite.js
- lib/svg-sprite/mode/base.js
- lib/svg-sprite/queue.js
> Fixed missing cpu information on nodejs

- README.md
Page with trailing slash gives 404 error
> Remove trailing slash

- README.md
- bin/config.yaml
- lib/svg-sprite/config.js
- lib/svg-sprite/shape.js
> added namespaceIDPrefix option

- lib/svg-sprite.js
- lib/svg-sprite/mode/base.js
- lib/svg-sprite/sprite.js
> Switch to `Buffer.from`

- lib/svg-sprite/config.js
- lib/svg-sprite/shape.js
- lib/svg-sprite/sprite.js
> Replace `_.isArray` with `Array.isArray`

- lib/svg-sprite.js
AFAICT the variables are all strings so it should be fine.
> Replace `_.trim` with native

- bin/svg-sprite.js
- example.js
- package.json
- test/svg-sprite.js
~~Requires #398 and I'll rebase it after~~
> Remove mkdirp

- bin/svg-sprite.js
- lib/svg-sprite.js
- lib/svg-sprite/layouter.js
- lib/svg-sprite/shape.js
So, this is definitely better IMHO as long as `string` isn't undefined.
> Replace indexOf with startsWith/endsWith

- package-lock.json
- package.json
- test/svg-sprite.js
> Replace image-diff with looks-same

- test/svg-sprite.js
> test/svg-sprite.js: specify encoding for `readFile`.

- package-lock.json
- package.json
> Remove useless puppeteer peerDependency

- .c8rc.json
Should show the real coverage for all files.
> Update c8 config

- lib/svg-sprite/calculate-svg-dimensions.js
- lib/svg-sprite/shape.js
- test/calculate-svg-dimensions.test.js
That is for increasing speed on win32 machines in CI
> fix: changing async to sync render with resvg

- .mocharc.json
- test/spriter.test.js
- test/svg-sprite.test.js
- test/svg-sprite/minimal-configuration/rerun.test.js
My point here to split tests by logical peaces.
One tests creation of files 
Second one just write those files before the actual visual regression tests
> feat: test refactoring

- bin/svg-sprite.js
- lib/svg-sprite.js
- lib/svg-sprite/config.js
- lib/svg-sprite/mode/base.js
- lib/svg-sprite/mode/css.js
- lib/svg-sprite/mode/standalone.js
- lib/svg-sprite/shape.js
- lib/svg-sprite/sprite.js
- lib/svg-sprite/utils/index.js
- test/helpers/write-files.js
- test/shape.test.js
- test/utils.test.js
As per comment in v2 beta release this decreases direct usage of Lodash:
> Reduced lodash usage (patches welcome to reduce its use further!)
- isFunction
- isObject
Additional gain should be a slight speed increase.
Thanks!
TODO:
> feat: decrease Lodash usage

- README.md
- docs/api.md
- lib/svg-sprite.js
- test/svg-sprite/minimal-configuration/error.test.js
- test/svg-sprite/minimal-configuration/no-arguments.test.js
> feat: adding async compile method (returns Promise)

- lib/svg-sprite/config.js
- lib/svg-sprite/mode/css.js
> Replace `_.pick` with native JS

- lib/svg-sprite.js
- lib/svg-sprite/layouter.js
- lib/svg-sprite/shape.js
- lib/svg-sprite/transform/svgo.js
@Kreeg It's not more readable, but feel free to push any changes to improve readability.
Split from #619 since that should probably land after we are done with all other lodash instances.
> Replace `_.cloneDeep` with `_.merge`

- lib/svg-sprite/config.js
- test/svg-sprite/config.test.js
> fix: checking passed config.log to be instance of winston.Logger

- lib/svg-sprite/layouter.js
It's safe since this file is totally covered by test
> Convert SVGSpriteLayouter to ES6 class

- test/svg-sprite/config/config.constructor.attributes.test.js
- test/svg-sprite/config/config.constructor.shape.align.test.js
- test/svg-sprite/config/config.constructor.shape.meta.test.js
> add tests for `shape.align` creation in SVGSpriterConfig

- lib/svg-sprite/mode/css.js
- lib/svg-sprite/mode/defs.js
- lib/svg-sprite/mode/stack.js
- lib/svg-sprite/mode/standalone.js
- lib/svg-sprite/mode/symbol.js
Not 100% sure about these, needs more eyes :)
> Replace deprecated getter/setter methods with `Object.defineProperty`

- lib/svg-sprite/config.js
10 more files left, I'll leave those to you @Kreeg :)
> Convert Config to an ES6 class

- lib/svg-sprite/shape.js
- test/svg-sprite/shape/shape.svg.namespace.test.js
- test/svg-sprite/shape/shape.svg.test.js
> Substitute ID references in href attributes 

- package-lock.json
- package.json
@XhmikosR new version brings back the old issue with different screenshot qualities with unplugged notebook. 
I fixed the version which is not causing this problem.
https://github.com/microsoft/playwright/issues/14460
> Downgrade playwright due to different screenshot quality with & without plugged power source

- bin/svg-sprite.js
- lib/svg-sprite.js
- lib/svg-sprite/layouter.js
- lib/svg-sprite/mode/base.js
- lib/svg-sprite/shape.js
- lib/svg-sprite/transform/svgo.js
- package-lock.json
- package.json
Refs #604 
We should probably try and land #463 and #616 first.
> Switch to the `lodash.merge` package

- lib/svg-sprite.js
@jkphl this seems to work, but I haven't checked if lodash did exactly the same.
Refs #604
> Replace `_.invoke` with vanilla JS

- docs/templating.md
- lib/svg-sprite/layouter.js
- test/svg-sprite/layouter.test.js
- tmpl/css/sprite.html
- tmpl/defs/sprite.html
- tmpl/stack/sprite.html
- tmpl/symbol/sprite.html
- tmpl/view/sprite.html
> Added filesize to example page

- lib/svg-sprite/shape.js
- test/svg-sprite/shape/shape.constructor.test.js
- test/svg-sprite/shape/shape.dimensions.test.js
- test/svg-sprite/shape/shape.distribute.test.js
- test/svg-sprite/shape/shape.init-svg.test.js
- test/svg-sprite/shape/shape.references.test.js
> Added tests for `SVGShape`

- lib/svg-sprite/shape.js
- test/svg-sprite/special/font-face.test.js
> Fixed #288: Preserving `@font-face` in style defs

- lib/svg-sprite.js
- lib/svg-sprite/queue.js
- lib/svg-sprite/shape.js
- test/svg-sprite/queue.test.js
- test/svg-sprite/shape/shape.complement.test.js
- test/svg-sprite/shape/shape.constructor.test.js
- test/svg-sprite/shape/shape.dimensions.test.js
- test/svg-sprite/shape/shape.distribute.test.js
- test/svg-sprite/shape/shape.init-svg.test.js
- test/svg-sprite/shape/shape.references.test.js
- test/svg-sprite/shape/shape.svg.namespace.test.js
- test/svg-sprite/shape/shape.svg.test.js
It should really fix #740 
I'll try to release a new 2.0.2 version after this is merged.
EDIT: BTW this doesn't seem to be covered by the tests, any help adding a test case is welcome :)
> lib/svg-sprite.js: revert change from e85b53c

- package-lock.json
- package.json
Change Log: https://github.com/yisibl/resvg-js/releases/tag/v2.2.0
> chore: upgrade resvg-js to 2.2.0

- bin/svg-sprite.js
- example.js
- lib/svg-sprite.js
- lib/svg-sprite/config.js
- lib/svg-sprite/layouter.js
- lib/svg-sprite/mode/base.js
- lib/svg-sprite/mode/css.js
- lib/svg-sprite/mode/css/packer.js
- lib/svg-sprite/mode/standalone.js
- lib/svg-sprite/mode/symbol.js
- lib/svg-sprite/shape.js
- lib/svg-sprite/utils/index.js
- test/helpers/add-files.js
@Kreeg this should be the last batch of patches. The only patch I'm not 100% sure is the "Simplify a few boolean checks" one.
Check the non-whitespace diff: https://github.com/svg-sprite/svg-sprite/pull/761/files?w=1
TODO:
> More refactoring

- lib/svg-sprite.js
- test/spriter.test.js
Fixes #762 
This could also close #770
> Fix `_transformShape` Not Calling All Transformations

- lib/svg-sprite.js
- test/spriter.test.js
> fix crash with spriter.add(..., null, ...)

- lib/svg-sprite.js
- lib/svg-sprite/utils/index.js
- package-lock.json
- package.json
> Backport the `lodash.trim` and `lodash.trimStart` removal to 2.x
