tmpl/symbol/sprite.html
Configuration field 'prefix' should contain first selector parts including class dot. To prevent duplication we remove one from template. 
https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#common-mode-properties
=> Remove "." (dot). Selector already has one.

docs/configuration.md
Current configuration.md shows custom template example incorrectly:
```javascript
{ 
mode: { 
css: { 
template: 'path'
}
}
}
```
should be: 
```javascript
{ 
mode: { 
css: { 
render: {
css: {
template: 'path'
}
}
}
}
}
```
=> updating example in configuration.md to show correct configuration

bin/svg-sprite.js
Documentation states that you can provide transform config json files using the argument "--shape-transform-*". The code actually looks for "--transform-*". Change fixes this to match the documented behaviour.
=> Fix incorrect lookup for shape-transform-* config

tmpl/css/sprite.less
Adds a dot before calling the less mixin otherwise this will generate syntax errors.
I'm using the following configuration in grunt-svg-sprite:
```
target: {
src: '../svgs/*',
dest: '.',
options: {
shape: {
id: {
generator: generatorFunc
},
dimension: {
maxWidth: 76,
maxHeight: 76
},
spacing: {
padding: 1
}
},
mode: {
css: {
bust: false,
mixin: 'svg-mysvgs-common',
sprite: '../img/Icons',
prefix: '.myPrefix-',
dimensions: true,
render: {
less: {
dest: '../src/less/somelessfile.less'
}
}
}
}
}
},
```
will generate something like:
```
.svg-mysvgs-common() {
background: url("../img/whatever.svg") no-repeat;
}
.myPrefix-some-svg {
svg-trait-small-common();
background-position: 16.666666666666668% 0;
width: 50px;
height: 50px;
}
```
in the output `svg-trait-small-common()` will cause a less …
=> Update sprite.less to avoid compilation error on mixin call

lib/svg-sprite/shape.js
I had an error that in some cases original `clip-path` attribute is absent in resulting sprite, in particular it's happening for attributes like `clip-path="url('#someID')"`
after debugging turned out that `svg-sprite` incorrectly handles quotes in `url()` - see this [jsbin](http://jsbin.com/bulinidota/edit?js,console)
so here's fix for this issue
=> Fix regexp to handle quotes in url()

lib/svg-sprite/config.js
The `getMonth` method returned a zero-based integer value for the month (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth), which would therefore be showing 1 month behind what the actual month is.
Example output from today (February 15th) which shows the issue:
The `Date.format` provides the same formatted date which the timestamp method was previously building manually.
=> Solve issue with showing incorrect month in log

bin/svg-sprite.js
According to the docs (https://github.com/jkphl/svg-sprite/blob/master/docs/command-line.md), a config file that's generated from the online config generator can be passed to the CLI. However, passing it the file wasn't able to read the SVGO transform plugins. This is because the CLI tries to do special string processing on the transform configuration.
This PR passes through the `shape.transform` config unless it is a string.
Example config file that was unable to process the svgo plugins:
```
{
"dest": "dist",
"shape": {
"transform": [
{
"svgo": {
"plugins": [
{ "removeUnknownsAndDefaults"    : false}
]
}
}
]
},
"mode": {
"symbol": {
"dest": ".",
"sprite": "ui.svg"
}
}
}
```
=> Allow for array transforms in config file to be passed to CLI

lib/svg-sprite/shape.js
I noticed the problem by adding precision `0` to the `shape.dimension`. The values were not rounded in the stylesheet. Then I looked around and it appeared that when the values are coming from the bounding box or from phantomjs they are not rounded at all. 
When loading the style into chrome I had issues with some svgs which were slightly taller. I get that the svgs should never have a width/height with decimals precision, but the plugin should also handle that.
=> Problem when dimensions are not rounded properly

lib/svg-sprite/transform/svgo.js, package.json
The optimize() function now returns a promise. Adapt the code to
behave correctly in this case.
We could also just keep the older svgo dependency.
=> Use more recent version of svgo

README.md
Currently, code blocks of documentation aren't so readable, b/c tabs formatting doesn't work so well on github. I replaced all tabs with 4 spaces and realigned vertically everything to look similar to current code.
=> Docs formatting update - all tabs replaced with spaces

bin/svg-sprite.js, lib/svg-sprite.js, lib/svg-sprite/mode/base.js, lib/svg-sprite/mode/symbol.js, lib/svg-sprite/queue.js, lib/svg-sprite/shape.js, package.json
Fixes JSHint errors that went uncaught. Adds linting as a `pretest` task, to avoid further errors.
I recommend switching from JSHint to ESLint and its `eslint:recommended` rules.
=> Enforce linting

lib/svg-sprite/shape.js
If user doesn't want to add file path to shape id
=> if shape.id.separator set to false or '' return shape id without file path separator (only filename)

package.json
Currently the tests do not run on Windows due to an issue in instanbul loading the mocha binary.
This PR fixes it.
https://github.com/generalov/gemini/commit/255d8518ce30d53b55f170df5ea94687ac7e3cf1
https://github.com/gotwarlost/istanbul/issues/13
https://github.com/gotwarlost/istanbul/issues/90
=> fix: use the mocha binary from node_modules

docs/configuration.md
Hi,
using this svgo plugin with svg-sprite according docs, I realized it's not working. So I figured out, this is an old reference. See https://github.com/svg/svgo/pull/980
Furthermore I set to false in this case to reflect you actually want to override the default.
Have a nice week
midzer
=> replace legacy plugin name by respective one

docs/templating.md, lib/svg-sprite/layouter.js
Creates an ability to generate scss file, which contains css classes such as 
.{{name}}-background {
background: url('data:image/svg+xml;utf-8,{{#escapeHashSign}}{{{svg}}}{{/escapeHashSign}}') no-repeat;
}
Some svg-files contain hash signs ('#') which make it impossible to use such svg's as data urls. Url encoding of the whole file should work but It's not always suitable to increase generated file size. So I found it appropriate to encode only hash signs symbols. Using the library in cli mode makes it impossible to pass custom variables function to generator so it's the simplest way to deal with it.
=> Escape hash sing built-in function

lib/svg-sprite/config.js, package-lock.json, package.json
As I described in the issue (#279), the verbose logging broke with an upgrade to `winston@3.x.x`, which dramatically changed its formatting API. This PR restores the log output to the original output format.
One discovery I've found is that Winston's timestamp functionality accepts its own date formatting string, which means that the `dateformat` dependency specified in this package is not strictly necessary. I am also proposing to remove that here.
=> Fix verbose logging output (closes #279)

lib/svg-sprite.js
Reverts jkphl/svg-sprite#408
`svg` seems to a buffer in one case. We should handle this more explicitly later so I'll revert this for now. Tests didn't catch this unfortunately...
=> Revert "Replace `_.trim` with native"

lib/svg-sprite/layouter.js
Not sure if this makes any difference performance-wise in this specific case.
=> layouter.js: cache length variable before the loop

lib/svg-sprite/shape.js, package-lock.json, package.json
cssmin is unmaintained and probably has bugs.
I went with csso because svgo is already using it, so it's not another dependency. I also went with `restructure: false` to be safe.
It doesn't seem there are tests for CSS minification, from a quick look.
~~Depends on #398 and I'll probably need to rebase later.~~
Doesn't fi x #365 but shouldn't break that case anymore.
This is basically untested!
We need a test case for this, but we should at least test it manually.
=> Replace cssmin with csso

lib/svg-sprite.js
`map` must have a `return`. I checked `setNamespace` and it doesn't seem to return anything, so this should probably be `forEach`.
Split from my lint branch.
=> svg-sprite.js: replace map with forEach

bin/svg-sprite.js
`argv._` is an array so we can safely use the native reduce function
=> Replace `_.reduce` with native JS

lib/svg-sprite/shape.js
Split from #436.
@jkphl XML is case sensitive, isn't it? If so, the regex shouldn't use the `i` flag, right?
=> shape.js: simplify ENTITY regex

bin/svg-sprite.js
Makes more sense to be consistent for the time.
Unfortunately, the CLI isn't tested, so let me know if everything still looks good @jkphl
=> bin/svg-sprite.js: use `_.merge` instead of the custom function

lib/svg-sprite.js
@jkphl bear with me here, I'm trying to be explicit and clearer. Instead of using `arguments` and shifting, the function accepts two parameters, which matches the jsDoc comments too.
Generally, optional parameters are at the end, though, but I tried to keep the previous behavior.
Split from #436
=> Make `SVGSpriter.compile()`'s arguments explicit

lib/svg-sprite/mode/css/packer.js
@jkphl this is a tricky one, so bear with me please :)
I attempted to make this clearer because previously it was impossible to follow the logic. I'm not 100% sure if our tests cover this so please review thoroughly.
Split from #436
=> packer.js: stop nesting ternary expressions

lib/svg-sprite.js, lib/svg-sprite/layouter.js, lib/svg-sprite/shape.js
@jkphl now this might hide some issues that went unnoticed until now.
It seems that the `isDeep` parameter was removed in lodash v4.0.0. There's the `cloneDeep` function, but I don't know if it's supposed to be used in these cases.
EDIT: we should really have tests for this. :/ Feel free to push a test.
=> Fix lodash cloneDeep usage

example.js, test/svg-sprite.js
`path.join` already normalizes the paths
=> Remove unneeded `path.normalize` calls

lib/svg-sprite/shape.js
=> Stop ignoring case for `xml` and `DOCTYPE`

README.md, bin/svg-sprite.js, docs/api.md, docs/grunt-gulp.md, example.js, test/svg-sprite.js
@jkphl not sure which solution you prefer, both work the same. This is shorter and now consistent.
=> `readFile`/`readFileSync`: use the string encoding option consistently

lib/svg-sprite/transform/svgo.js
The options `config.svg.xmlDeclaration` and `config.svg.doctypeDeclaration` will now have these effects:
- `false` -> remove
- `true` -> keep
- empty string -> remove
- non empty string -> keep (will be set to the value later)
This should follow their [documentation](https://github.com/svg-sprite/svg-sprite/blob/9c8a4a6f0830d14e46e2c02542366ed485f88bdc/docs/configuration.md#sprite-svg-options).
It'll use `preset-default` if no svgo plugin configuration is set.
fixes #523
cc @XhmikosR
=> config: Fix `xmlDeclaration` and `doctypeDeclaration`

lib/svg-sprite/mode/base.js
It's a "private" function and we always pass a unit
=> _addUnit(): remove unneeded fallback

lib/svg-sprite/fix-xml-string.js, lib/svg-sprite/shape.js, test/fix-xml-string.test.js, test/svg-shape.test.js
+ some JSDoc fixes
Suggestion: moving from `mocha` to `jest`. Current problem is with inability of mocking modules. For example in `test/svg-shape.test.js` I have to copy-paste test input strings from  `test/fix-xml-string.test.js` instead of mocking `lib/svg-sprite/fix-xml-string.js` behavior. 
But there is two problems: 
1. Jest is a BIG package
2. Current test dependency. All test a designed to run step-by-step, but jest is designed to run parallel tests with random orde
Fixes #454
=> fix: fixing valid svg checking

lib/svg-sprite.js, test/spriter.test.js, test/svg-sprite.test.js
This commit ensures that input files' path is resolved *before* it's split into a base path and full path. Indeed, Shape's constructor builds shape names as follows:
```
this.name = this.source.path.substr(this.source.base.length + path.sep.length);
```
With the current code, only the source file's base is resolved, and so, `source.base` is longer than `source.path`, and the whole path gets destroyed, resulting in `this.name` being an empty string.
With the proposed change, shape names are now correct even when input files have a relative path.
Note that the `else` branch was used to ensure consistent behaviour with previous code; though I'm unsure what the purpose of `file.base = path.resolve(file.base);` is.
=> Fix missing shape names when adding input files with a relative path

lib/svg-sprite/calculate-svg-dimensions.js, test/calculate-svg-dimensions.test.js, test/helpers/resvg-preheat.js, test/svg-sprite.test.js
Try to fix: https://github.com/svg-sprite/svg-sprite/pull/574#issuecomment-1053551158
resvg-js loads all system fonts by default, which is more time consuming on first startup and is cached after startup, which explains why preloading resvg-js tests once makes them faster.
We don't need this feature by default, so disable this option. This can greatly improve the speed of svg-sprite the first time it is started.
This PR also removes `fitTo: { mode: 'original' }` option, as it is the default value.
=> feat: disable loadSystemFonts in resvg-js to improve first-time loading speed

package.json
Before:
```
npm notice === Tarball Details ===
npm notice name:          svg-sprite
npm notice version:       2.0.0-beta1
npm notice filename:      svg-sprite-2.0.0-beta1.tgz
npm notice package size:  59.7 kB
npm notice unpacked size: 278.1 kB
npm notice shasum:        b2dbac9ce5d7745b0ed1baf7d40b48519bd7fac7
npm notice integrity:     sha512-ZJ7y5+Jb2Lqir[...]YOQGEGYQ8qF1g==
npm notice total files:   42
```
After:
```
npm notice === Tarball Details ===
npm notice name:          svg-sprite
npm notice version:       2.0.0-beta1
npm notice filename:      svg-sprite-2.0.0-beta1.tgz
npm notice package size:  41.4 kB
npm notice unpacked size: 198.6 kB
npm notice shasum:        fd145049422b3c3b2e70766cdb647cc3bfae599e
npm notice integrity:     sha512-h2S37uq2liqrR[...]joQ7WmVJY5BHQ==
npm notice …
```
=> package.json: stop including docs

lib/svg-sprite/shape.js
Before:
```
C:\Users\xmr\Desktop\svg-sprite>hyperfine "node ..\load-time.js"
Benchmark 1: node ..\load-time.js
Time (mean ± σ):     422.1 ms ±  26.4 ms    [User: 3.1 ms, System: 1.1 ms]
Range (min … max):   396.5 ms … 472.4 ms    10 runs
```
After:
```
C:\Users\xmr\Desktop\svg-sprite>hyperfine "node ..\load-time.js"
Benchmark 1: node ..\load-time.js
Time (mean ± σ):     392.3 ms ±   7.8 ms    [User: 1.3 ms, System: 8.0 ms]
Range (min … max):   383.3 ms … 406.0 ms    10 runs
```
Closes #570 
I don't love these, but with this patch and most noticeably #585, we are back to the load time of 1.5.4.
There's still a difference, probably coming from js-yaml 4 (#419), but I don't think we can do anything here.
=> shape: move calculate-svg-dimensions require where it's used

package-lock.json, package.json
It's the same version used by svgo so this reduces the deps
@Kreeg just a reminder so that you don't accidentally merge a dependabot PR in the future unless svgo is updated to use csso@5 too :)
I'm still not sure if this works properly but anyway, the less packages, the better.
=> Downgrade csso to v4.

docs/configuration.md, test/tmpl/css.html, test/tmpl/symbol.html, test/tmpl/view.html, tmpl/css/sprite.html, tmpl/defs/sprite.html, tmpl/stack/sprite.html, tmpl/symbol/sprite.html, tmpl/view/sprite.html
* switch to plain `doctype`
* remove unneeded type=text/css from style attributes
* beautify CSS
* remove svg4everybody
I only checked the CSS mode, need more eyes for the rest :)
=> Template tweaks and drop Internet Explorer support

.github/workflows/test.yml, package.json
We could also just drop them since one can do `npx jest --foo` or `npm run jest -- --foo`, but I guess it doesn't hurt.
=> Rename npm scripts

lib/svg-sprite/sprite.js, lib/svg-sprite/utils/index.js, test/utils.test.js
Refs #604
An alternative solution would be to go with a separate (small) package, which is an acceptable solution too, assuming we finish with all other lodash instances.
=> Replace `_.escape` with native JS

lib/svg-sprite/sprite.js, lib/svg-sprite/utils/index.js, package-lock.json, package.json, test/utils.test.js
Fixes #702 
@Kreeg as much as I hate adding more deps it seems our implementation was too naive :/
Lodash escape is doing this:
```js
function escape(string) {
string = toString(string);
return (string && reHasUnescapedHtml.test(string))
? string.replace(reUnescapedHtml, escapeHtmlChar)
: string;
}
```
Unsure if we can easily fix the issue but if not, I made this PR so that we can land it.
TODO:
=> Revert 620

package-lock.json, package.json
resvg-js 2.1.0 change Log: https://github.com/yisibl/resvg-js/releases/tag/v2.1.0
=> chore: upgrade resvg-js to 2.1.0

README.md
'inline' isn't a mode. 'inline' is a config property for the 'symbol'
mode. Fix the example in the docs to set the intended property.
=> fix(docs): fix example config for inline symbols

lib/svg-sprite.js
SVGSpriter.prototype.add is called with Buffer instances in some tests, and that seems to be intentionally supported. Fix the outdated JSDoc which says that only strings are allowed.
=> fix(docs): fix incorrect type annotation

lib/svg-sprite/shape.js, test/svg-sprite/shape/shape.constructor.test.js
Hi!
I created a fork to fix the problem reported here: #740
Regards
Fixes #740
=> Fix `shape.id.separator` regression

.github/workflows/lint.yml, .github/workflows/test.yml
=> CI: switch to Node.js 18

lib/svg-sprite.js, package-lock.json, package.json
=> refactor: drop `lodash.trim` dependency

README.md, bin/svg-sprite.js, docs/api.md, example.js, lib/svg-sprite.js, lib/svg-sprite/config.js, lib/svg-sprite/layouter.js, lib/svg-sprite/mode/base.js, lib/svg-sprite/mode/css.js, lib/svg-sprite/mode/css/packer.js, lib/svg-sprite/mode/stack.js, lib/svg-sprite/mode/standalone.js, lib/svg-sprite/mode/symbol.js, lib/svg-sprite/mode/view.js, lib/svg-sprite/shape.js, lib/svg-sprite/sprite.js, package.json, test/helpers/add-files.js, test/helpers/write-files.js, test/svg-shape.test.js, test/svg-sprite/shape/shape.svg.namespace.test.js
For...of is more consistent and this way we don't need to explicitly check for own properties.
That being said, I hit a case where an error was thrown so I had to add a fallback, which means we could probably improve that part: https://github.com/svg-sprite/svg-sprite/pull/591/files#diff-79d35363069d02f38101ba80dad33c3dd32e39f32af88131c3365a3001a14b47R186
```js
for (const [extension, value] of Object.entries(this.config.render || {})) {
tasks.push(createResourceTask(value, this.data, this._spriter, extension));
}
```
Also, unfortunately, the current tests don't cover everything yet.
TODO:
=> Use for...of loops when possible

lib/svg-sprite/config.js, lib/svg-sprite/errors/argument-error.js, lib/svg-sprite/errors/dimensions-calculation-error.js, lib/svg-sprite/errors/not-permitted-error.js, lib/svg-sprite/errors/xml-fixing-error.js, lib/svg-sprite/mode/base.js, package-lock.json, package.json, test/spriter.test.js, test/svg-sprite/config/config.constructor.shape.align.test.js, test/svg-sprite/config/config.constructor.shape.meta.test.js, test/svg-sprite/minimal-configuration/modes/css.test.js, test/svg-sprite/shape/shape.complement.test.js, test/svg-sprite/shape/shape.init-svg.test.js, test/svg-sprite/shape/shape.svg.test.js, test/svg-sprite/special/font-face.test.js
@Kreeg: I haven't updated playwright-chromium due to that old issue you were facing. I assume you are still facing it with the latest version, right?
The only other deps that are outdated is glob and pngjs. For glob there's no hurry and in fact we better keep it to v7.x for now. pngjs I didn't try to update it, so if you have time feel free to update it :)
=> Update devDependencies and fix new issues

jest.config.js
The time difference hit isn't that big. We might even want to go with `os.cpus() - 4` or `os.cpus() / 2`.
Now Jest doesn't spawn 600 processes on my Windows VM.
CI seems to be slower, though. We could use a different number of threads for CI.
=> Jest: limit maxWorkers, maxConcurrency and use workerThreads

lib/svg-sprite.js, package-lock.json, package.json
```
C:\Users\xmr\Desktop\svg-sprite>git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
C:\Users\xmr\Desktop\svg-sprite>hyperfine "node load-time.js"
Benchmark 1: node load-time.js
Time (mean ± σ):     218.0 ms ±  12.5 ms    [User: 185.0 ms, System: 69.4 ms]
Range (min … max):   204.4 ms … 243.4 ms    13 runs
C:\Users\xmr\Desktop\svg-sprite>git checkout -
Switched to branch 'xmr/import-lazy'
C:\Users\xmr\Desktop\svg-sprite>hyperfine "node load-time.js"
Benchmark 1: node load-time.js
Time (mean ± σ):      37.7 ms ±   1.6 ms    [User: 21.6 ms, System: 19.2 ms]
Range (min … max):    35.6 ms …  44.8 ms    68 runs
```
load-time.js:
```js
'use strict';
console.log('Load time');
console.time('Module');
exports.m = require('.');
console.timeEnd('Module');
``` …
=> Use import-lazy to speed up module load time

docs/shape-alignment.md
Fixed typo in docs/shape-alignment.md
Remember that the omitting the placeholder...
has changed to:
Remember that omitting the placeholder...
=> docs: Fix typo in shape-alignment.md

.github/workflows/test.yml
This should hopefully speed things up.
=> CI: only use Node.js 18 on macOS and Windows

README.md, docs/grunt-gulp.md
Noticed some incorrect links for grunt in the docs, just updating to correct repo. Thanks for the library.
=> fixing grunt-svg-sprite links in docs

.github/workflows/test.yml, package-lock.json, package.json
Although, we kept Node.js 14 compatibility in v3 so far, it's been a long time Node.js 14 is unsupported and we haven't released v3.0.0 stable yet.
TODO:
=> Drop Node.js < 16 support

lib/svg-sprite/shape.js, package-lock.json, package.json
This works around xmldom versions greater than 0.8.8 & up to 0.8.10 seemingly not supporting use of Object.keys on NodeList to iterate over currently existing keys.
It should be noted I have not investigated whether `Object.keys(NodeList)` is allowed per DOM specification and it could be that there exists a regression in xmldom. Track https://github.com/xmldom/xmldom/issues/583 for relevant discussion.
Original patch from https://github.com/svg-sprite/svg-sprite/pull/835#issuecomment-1822484800
=> Replace iterating over `Object.keys(NodeList)` with `NodeList.length`
